version: '3.8'
services:
  api:
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ||workspaceFolder||:/opt/src
    environment:
      - EXECMD=python3 app.py
      - APPPORT=8000
      - ENDPOINTS=getrace,racetrack,dist,gimmeflag,test
      - LANGUAGE=python
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 15s
      timeout: 10s
      retries: 10

  nuclei_runner:
    image: projectdiscovery/nuclei
    volumes:
      - ||templateFolder||:/app/templates
      - ||payloadsFolder||:/app/payloads
      - ./results:/app/results
    # command: -jsonl /app/results/results.jsonl -u http://api:8000 -t /app/templates/
    command: /bin/sh -c "chmod -R 777 /app/templates /app/payloads && nuclei -u http://api:8000 -t /app/templates/ -v -validate"
    depends_on:
      api:
        condition: service_healthy
