version: '3.8'
services:
  api:
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - c:\Users\Gabriel\Desktop\School\Y2T2\ICT2214 - Web Security\reposhield\demo:/opt/src
    environment:
      - EXECMD=python3 app.py
      - APPPORT=8000
      - ENDPOINTS=getrace,racetrack,dist,gimmeflag,test
      - LANGUAGE=python
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 15s
      timeout: 10s
      retries: 10

  nuclei_runner:
    # image: projectdiscovery/nuclei
    build:
      context: ./nuclei
      dockerfile: Dockerfile
    volumes:
      - c:\Users\Gabriel\Desktop\School\Y2T2\ICT2214 - Web Security\reposhield\reposhield\resources\nuclei\templates:/app/templates
      - c:\Users\Gabriel\Desktop\School\Y2T2\ICT2214 - Web Security\reposhield\demo\.reposhield\nuclei:/app/results
    depends_on:
      api:
        condition: service_healthy
