version: '3.8'
services:
  api:
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ||workspaceFolder||:/opt/src
    environment:
      - EXECMD=python3 app.py
      - APPPORT=8000
      - ENDPOINTS=getrace,racetrack,dist,gimmeflag,test
      - LANGUAGE=python
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 15s
      timeout: 10s
      retries: 10

  nuclei_runner:
    # image: projectdiscovery/nuclei
    build:
      context: ./nuclei
      dockerfile: Dockerfile
    volumes:
      - ||templateFolder||:/app/templates
      - ./results:/app/results
    depends_on:
      api:
        condition: service_healthy
